module.exports = {
  transform: {
    "^.+\\.[jt]sx?$": [
      "babel-jest",
      {
        caller: {
          name: "metro",
          bundler: "metro",
          platform: "ios",
          preserveEnvVars: true,
        },
      },
    ],
  },
  preset: "jest-expo",
  testEnvironment: "jsdom",
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
  transformIgnorePatterns: [
    "node_modules/(?!((jest-)?react-native|@react-native(?:[\\/].*)?|react-native-.*|@react-navigation|@react-native-community|expo(?:-.*)?|@expo/.*|expo-modules-core|@unimodules|@react-native-async-storage|@gorhom|moti|solito|dripsy|nativewind|vaul|@react-native-js-polyfills|@rn-primitives(?:[\\/].*)?)/)",
  ],
  roots: [
    "<rootDir>/app",
    "<rootDir>/components",
    "<rootDir>/hooks",
    "<rootDir>/stores",
    "<rootDir>/theme",
    "<rootDir>/types",
    "<rootDir>/utils",
    "<rootDir>/supabase",
    "<rootDir>/scripts",
    "<rootDir>/__tests__",
  ],
  testMatch: ["**/?(*.)+(test).[jt]s?(x)"],
  testPathIgnorePatterns: [
    "/node_modules/",
    "/tests-e2e/", // skip your Detox/E2E suite for now
    "/recovery/",
    "/artifacts/",
  ],
  collectCoverageFrom: [
    "<rootDir>/app/(dashboard)/index.tsx",
    "<rootDir>/app/(dashboard)/step/**/*.{ts,tsx}",
    "<rootDir>/components/common/**/*.{ts,tsx}",
    "<rootDir>/components/dashboard/**/*.{ts,tsx}",
    "<rootDir>/components/state/**/*.{ts,tsx}",
    "<rootDir>/components/trust/**/*.{ts,tsx}",
    "<rootDir>/components/ui/**/*.{ts,tsx}",
    "<rootDir>/hooks/useAppTheme.ts",
    "<rootDir>/hooks/useErrorBanner.ts",
    "<rootDir>/stores/**/*.{ts,tsx}",
    "<rootDir>/utils/**/*.{ts,tsx}",
    "<rootDir>/supabase/functions/_shared/**/*.{ts,tsx}",
    "<rootDir>/supabase/functions/**/auth.ts",
    "<rootDir>/supabase/functions/agentGateway/providerInvocation.ts",
    "<rootDir>/scripts/validate-env.mjs",
    "<rootDir>/scripts/milestone-6-phase-a-check.mjs",
    "<rootDir>/scripts/milestone-6-ingestion-check.mjs",
    "<rootDir>/scripts/schema-sync.mjs",
    "<rootDir>/scripts/scan-tracked-secrets.mjs",
    "!**/*.d.ts",
    "!**/*.test.{ts,tsx,js,mjs,cjs}",
    "!<rootDir>/**/__tests__/**",
    "!<rootDir>/**/__mocks__/**",
    "!<rootDir>/**/__fixtures__/**",
    "!<rootDir>/components/**/index.ts",
    "!<rootDir>/components/**/index.tsx",
    "!<rootDir>/utils/contracts/**/*.ts",
    "!<rootDir>/utils/testUtils.ts",
  ],
  modulePathIgnorePatterns: ["<rootDir>/recovery/", "<rootDir>/artifacts/"],
  coverageThreshold: {
    // Global floor over an explicit cross-surface file set.
    global: {
      statements: 40,
      branches: 30,
      functions: 45,
      lines: 40,
    },
    "./supabase/functions/**/auth.ts": {
      statements: 100,
      branches: 80,
      functions: 100,
      lines: 100,
    },
  },
  moduleNameMapper: {
    "^react-native$": "react-native-web",
    "^@/(.*)": "<rootDir>/$1",
    "^@/app/(.*)": "<rootDir>/app/$1",
    "^@/components/(.*)": "<rootDir>/components/$1",
    "^@/utils/(.*)": "<rootDir>/utils/$1",
    "^@/types/(.*)": "<rootDir>/types/$1",
    "^@test-utils$": "<rootDir>/__tests__/utils/test-utils.tsx",
  },
};
