// Generated by npm run supabase:gen:types
// Source project ref: zderaqrvjljvkwhilesp
// Generated at: 2026-02-28T10:32:41.671Z

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1";
  };
  public: {
    Tables: {
      accounts: {
        Row: {
          account_name: string | null;
          account_subtype: string | null;
          account_type: string | null;
          balance: number | null;
          created_at: string;
          id: string;
          institution_id: string | null;
          institution_name: string | null;
          iso_currency_code: string | null;
          plaid_account_id: string;
          plaid_item_id: string | null;
          updated_at: string;
          user_id: string | null;
        };
        Insert: {
          account_name?: string | null;
          account_subtype?: string | null;
          account_type?: string | null;
          balance?: number | null;
          created_at?: string;
          id?: string;
          institution_id?: string | null;
          institution_name?: string | null;
          iso_currency_code?: string | null;
          plaid_account_id: string;
          plaid_item_id?: string | null;
          updated_at?: string;
          user_id?: string | null;
        };
        Update: {
          account_name?: string | null;
          account_subtype?: string | null;
          account_type?: string | null;
          balance?: number | null;
          created_at?: string;
          id?: string;
          institution_id?: string | null;
          institution_name?: string | null;
          iso_currency_code?: string | null;
          plaid_account_id?: string;
          plaid_item_id?: string | null;
          updated_at?: string;
          user_id?: string | null;
        };
        Relationships: [];
      };
      agent_invocation_logs: {
        Row: {
          capability: string;
          created_at: string;
          error_message: string | null;
          id: string;
          latency_ms: number | null;
          provider_key: string;
          request_payload: Json;
          response_payload: Json | null;
          status: string;
          user_id: string | null;
        };
        Insert: {
          capability: string;
          created_at?: string;
          error_message?: string | null;
          id?: string;
          latency_ms?: number | null;
          provider_key: string;
          request_payload?: Json;
          response_payload?: Json | null;
          status: string;
          user_id?: string | null;
        };
        Update: {
          capability?: string;
          created_at?: string;
          error_message?: string | null;
          id?: string;
          latency_ms?: number | null;
          provider_key?: string;
          request_payload?: Json;
          response_payload?: Json | null;
          status?: string;
          user_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "agent_invocation_logs_provider_key_fkey";
            columns: ["provider_key"];
            isOneToOne: false;
            referencedRelation: "agent_providers";
            referencedColumns: ["provider_key"];
          },
        ];
      };
      agent_providers: {
        Row: {
          auth_type: string;
          capabilities: string[];
          created_at: string;
          description: string | null;
          display_name: string;
          endpoint_url: string | null;
          id: string;
          metadata: Json;
          provider_key: string;
          status: string;
          updated_at: string;
        };
        Insert: {
          auth_type?: string;
          capabilities?: string[];
          created_at?: string;
          description?: string | null;
          display_name: string;
          endpoint_url?: string | null;
          id?: string;
          metadata?: Json;
          provider_key: string;
          status?: string;
          updated_at?: string;
        };
        Update: {
          auth_type?: string;
          capabilities?: string[];
          created_at?: string;
          description?: string | null;
          display_name?: string;
          endpoint_url?: string | null;
          id?: string;
          metadata?: Json;
          provider_key?: string;
          status?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      fme_evaluation_logs: {
        Row: {
          artifact_signature: string | null;
          created_at: string;
          evaluation_signature: string | null;
          facts_hash: string | null;
          facts_summary: Json | null;
          id: string;
          output_summary: Json;
          policy_versions: Json;
          rule_version: number | null;
          trace: Json | null;
          user_id: string;
        };
        Insert: {
          artifact_signature?: string | null;
          created_at?: string;
          evaluation_signature?: string | null;
          facts_hash?: string | null;
          facts_summary?: Json | null;
          id?: string;
          output_summary: Json;
          policy_versions: Json;
          rule_version?: number | null;
          trace?: Json | null;
          user_id: string;
        };
        Update: {
          artifact_signature?: string | null;
          created_at?: string;
          evaluation_signature?: string | null;
          facts_hash?: string | null;
          facts_summary?: Json | null;
          id?: string;
          output_summary?: Json;
          policy_versions?: Json;
          rule_version?: number | null;
          trace?: Json | null;
          user_id?: string;
        };
        Relationships: [];
      };
      insights: {
        Row: {
          body: string | null;
          created_at: string;
          id: string;
          metadata: Json;
          status: string;
          title: string;
          updated_at: string;
          user_id: string | null;
        };
        Insert: {
          body?: string | null;
          created_at?: string;
          id?: string;
          metadata?: Json;
          status?: string;
          title: string;
          updated_at?: string;
          user_id?: string | null;
        };
        Update: {
          body?: string | null;
          created_at?: string;
          id?: string;
          metadata?: Json;
          status?: string;
          title?: string;
          updated_at?: string;
          user_id?: string | null;
        };
        Relationships: [];
      };
      pending_insights: {
        Row: {
          created_at: string;
          error_message: string | null;
          id: string;
          payload: Json;
          plaid_env: string | null;
          processed_at: string | null;
          status: string;
          user_id: string | null;
          webhook_id: string | null;
        };
        Insert: {
          created_at?: string;
          error_message?: string | null;
          id?: string;
          payload?: Json;
          plaid_env?: string | null;
          processed_at?: string | null;
          status?: string;
          user_id?: string | null;
          webhook_id?: string | null;
        };
        Update: {
          created_at?: string;
          error_message?: string | null;
          id?: string;
          payload?: Json;
          plaid_env?: string | null;
          processed_at?: string | null;
          status?: string;
          user_id?: string | null;
          webhook_id?: string | null;
        };
        Relationships: [];
      };
      plaid_items: {
        Row: {
          created_at: string;
          encrypted_plaid_access_token: string;
          id: string;
          institution_id: string | null;
          institution_name: string | null;
          plaid_item_id: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          encrypted_plaid_access_token: string;
          id?: string;
          institution_id?: string | null;
          institution_name?: string | null;
          plaid_item_id: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          encrypted_plaid_access_token?: string;
          id?: string;
          institution_id?: string | null;
          institution_name?: string | null;
          plaid_item_id?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      policy_ops_admins: {
        Row: {
          active: boolean;
          added_by_user_id: string | null;
          created_at: string;
          notes: string | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          active?: boolean;
          added_by_user_id?: string | null;
          created_at?: string;
          notes?: string | null;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          active?: boolean;
          added_by_user_id?: string | null;
          created_at?: string;
          notes?: string | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      policy_ops_audits: {
        Row: {
          action: string;
          actor_user_id: string | null;
          artifact_signature: string | null;
          created_at: string;
          domain: string;
          id: string;
          jurisdiction: string;
          metadata: Json;
          operation_signature: string | null;
          region: string;
          source_version: number | null;
          target_version: number | null;
        };
        Insert: {
          action: string;
          actor_user_id?: string | null;
          artifact_signature?: string | null;
          created_at?: string;
          domain: string;
          id?: string;
          jurisdiction?: string;
          metadata?: Json;
          operation_signature?: string | null;
          region?: string;
          source_version?: number | null;
          target_version?: number | null;
        };
        Update: {
          action?: string;
          actor_user_id?: string | null;
          artifact_signature?: string | null;
          created_at?: string;
          domain?: string;
          id?: string;
          jurisdiction?: string;
          metadata?: Json;
          operation_signature?: string | null;
          region?: string;
          source_version?: number | null;
          target_version?: number | null;
        };
        Relationships: [];
      };
      policy_packs: {
        Row: {
          approved_at: string | null;
          created_at: string;
          domain: string;
          effective_from: string;
          effective_to: string | null;
          id: string;
          jurisdiction: string;
          pack: Json;
          region: string;
          source: Json | null;
          status: string;
          updated_at: string;
          version: number;
        };
        Insert: {
          approved_at?: string | null;
          created_at?: string;
          domain: string;
          effective_from: string;
          effective_to?: string | null;
          id?: string;
          jurisdiction?: string;
          pack: Json;
          region: string;
          source?: Json | null;
          status?: string;
          updated_at?: string;
          version: number;
        };
        Update: {
          approved_at?: string | null;
          created_at?: string;
          domain?: string;
          effective_from?: string;
          effective_to?: string | null;
          id?: string;
          jurisdiction?: string;
          pack?: Json;
          region?: string;
          source?: Json | null;
          status?: string;
          updated_at?: string;
          version?: number;
        };
        Relationships: [];
      };
      raw_transactions: {
        Row: {
          created_at: string;
          error_message: string | null;
          id: string;
          plaid_env: string | null;
          plaid_item_id: string;
          processed_at: string | null;
          status: string;
          webhook_id: string | null;
          webhook_payload: Json;
        };
        Insert: {
          created_at?: string;
          error_message?: string | null;
          id?: string;
          plaid_env?: string | null;
          plaid_item_id: string;
          processed_at?: string | null;
          status?: string;
          webhook_id?: string | null;
          webhook_payload?: Json;
        };
        Update: {
          created_at?: string;
          error_message?: string | null;
          id?: string;
          plaid_env?: string | null;
          plaid_item_id?: string;
          processed_at?: string | null;
          status?: string;
          webhook_id?: string | null;
          webhook_payload?: Json;
        };
        Relationships: [];
      };
      rule_packs: {
        Row: {
          approved_at: string | null;
          created_at: string;
          effective_from: string;
          effective_to: string | null;
          id: string;
          pack: Json;
          region: string;
          source: Json | null;
          status: string;
          updated_at: string;
          version: number;
        };
        Insert: {
          approved_at?: string | null;
          created_at?: string;
          effective_from: string;
          effective_to?: string | null;
          id?: string;
          pack: Json;
          region: string;
          source?: Json | null;
          status?: string;
          updated_at?: string;
          version: number;
        };
        Update: {
          approved_at?: string | null;
          created_at?: string;
          effective_from?: string;
          effective_to?: string | null;
          id?: string;
          pack?: Json;
          region?: string;
          source?: Json | null;
          status?: string;
          updated_at?: string;
          version?: number;
        };
        Relationships: [];
      };
      transactions: {
        Row: {
          amount: number;
          category: string[] | null;
          created_at: string;
          id: string;
          iso_currency_code: string | null;
          name: string;
          pending: boolean | null;
          plaid_account_id: string;
          plaid_item_id: string;
          plaid_transaction_id: string;
          transaction_date: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          amount: number;
          category?: string[] | null;
          created_at?: string;
          id?: string;
          iso_currency_code?: string | null;
          name: string;
          pending?: boolean | null;
          plaid_account_id: string;
          plaid_item_id: string;
          plaid_transaction_id: string;
          transaction_date: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          amount?: number;
          category?: string[] | null;
          created_at?: string;
          id?: string;
          iso_currency_code?: string | null;
          name?: string;
          pending?: boolean | null;
          plaid_account_id?: string;
          plaid_item_id?: string;
          plaid_transaction_id?: string;
          transaction_date?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      user_goals: {
        Row: {
          cadence: string | null;
          created_at: string;
          due_date: string | null;
          id: string;
          milestone_note: string | null;
          name: string;
          saved_amount: number;
          status: string;
          target_amount: number;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          cadence?: string | null;
          created_at?: string;
          due_date?: string | null;
          id?: string;
          milestone_note?: string | null;
          name: string;
          saved_amount?: number;
          status?: string;
          target_amount: number;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          cadence?: string | null;
          created_at?: string;
          due_date?: string | null;
          id?: string;
          milestone_note?: string | null;
          name?: string;
          saved_amount?: number;
          status?: string;
          target_amount?: number;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      user_push_tokens: {
        Row: {
          device_os: string | null;
          expo_push_token: string;
          id: string;
          last_seen_at: string | null;
          user_id: string | null;
        };
        Insert: {
          device_os?: string | null;
          expo_push_token: string;
          id?: string;
          last_seen_at?: string | null;
          user_id?: string | null;
        };
        Update: {
          device_os?: string | null;
          expo_push_token?: string;
          id?: string;
          last_seen_at?: string | null;
          user_id?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      bytea_to_text: { Args: { data: string }; Returns: string };
      http: {
        Args: { request: Database["public"]["CompositeTypes"]["http_request"] };
        Returns: Database["public"]["CompositeTypes"]["http_response"];
        SetofOptions: {
          from: "http_request";
          to: "http_response";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      http_delete:
        | {
            Args: { uri: string };
            Returns: Database["public"]["CompositeTypes"]["http_response"];
            SetofOptions: {
              from: "*";
              to: "http_response";
              isOneToOne: true;
              isSetofReturn: false;
            };
          }
        | {
            Args: { content: string; content_type: string; uri: string };
            Returns: Database["public"]["CompositeTypes"]["http_response"];
            SetofOptions: {
              from: "*";
              to: "http_response";
              isOneToOne: true;
              isSetofReturn: false;
            };
          };
      http_get:
        | {
            Args: { uri: string };
            Returns: Database["public"]["CompositeTypes"]["http_response"];
            SetofOptions: {
              from: "*";
              to: "http_response";
              isOneToOne: true;
              isSetofReturn: false;
            };
          }
        | {
            Args: { data: Json; uri: string };
            Returns: Database["public"]["CompositeTypes"]["http_response"];
            SetofOptions: {
              from: "*";
              to: "http_response";
              isOneToOne: true;
              isSetofReturn: false;
            };
          };
      http_head: {
        Args: { uri: string };
        Returns: Database["public"]["CompositeTypes"]["http_response"];
        SetofOptions: {
          from: "*";
          to: "http_response";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      http_header: {
        Args: { field: string; value: string };
        Returns: Database["public"]["CompositeTypes"]["http_header"];
        SetofOptions: {
          from: "*";
          to: "http_header";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      http_list_curlopt: {
        Args: never;
        Returns: {
          curlopt: string;
          value: string;
        }[];
      };
      http_patch: {
        Args: { content: string; content_type: string; uri: string };
        Returns: Database["public"]["CompositeTypes"]["http_response"];
        SetofOptions: {
          from: "*";
          to: "http_response";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      http_post:
        | {
            Args: { content: string; content_type: string; uri: string };
            Returns: Database["public"]["CompositeTypes"]["http_response"];
            SetofOptions: {
              from: "*";
              to: "http_response";
              isOneToOne: true;
              isSetofReturn: false;
            };
          }
        | {
            Args: { data: Json; uri: string };
            Returns: Database["public"]["CompositeTypes"]["http_response"];
            SetofOptions: {
              from: "*";
              to: "http_response";
              isOneToOne: true;
              isSetofReturn: false;
            };
          };
      http_put: {
        Args: { content: string; content_type: string; uri: string };
        Returns: Database["public"]["CompositeTypes"]["http_response"];
        SetofOptions: {
          from: "*";
          to: "http_response";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      http_reset_curlopt: { Args: never; Returns: boolean };
      http_set_curlopt: {
        Args: { curlopt: string; value: string };
        Returns: boolean;
      };
      rollup_net_worth: {
        Args: { p_days?: number; p_since: string; p_user_id: string };
        Returns: {
          day: string;
          expenses: number;
          income: number;
          net_worth: number;
        }[];
      };
      text_to_bytea: { Args: { data: string }; Returns: string };
      urlencode:
        | { Args: { data: Json }; Returns: string }
        | {
            Args: { string: string };
            Returns: {
              error: true;
            } & "Could not choose the best candidate function between: public.urlencode(string => bytea), public.urlencode(string => varchar). Try renaming the parameters or the function itself in the database so function overloading can be resolved";
          }
        | {
            Args: { string: string };
            Returns: {
              error: true;
            } & "Could not choose the best candidate function between: public.urlencode(string => bytea), public.urlencode(string => varchar). Try renaming the parameters or the function itself in the database so function overloading can be resolved";
          };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      http_header: {
        field: string | null;
        value: string | null;
      };
      http_request: {
        method: unknown;
        uri: string | null;
        headers: Database["public"]["CompositeTypes"]["http_header"][] | null;
        content_type: string | null;
        content: string | null;
      };
      http_response: {
        status: number | null;
        content_type: string | null;
        headers: Database["public"]["CompositeTypes"]["http_header"][] | null;
        content: string | null;
      };
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
