#!/usr/bin/env node

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..", "..", "..", "..");
const configuredMemoryDir = process.env.CODEX_AUTOPILOT_MEMORY_DIR;
const memoryDir = configuredMemoryDir
  ? path.resolve(configuredMemoryDir)
  : path.join(repoRoot, ".agents", "memory");
const eventsPath = path.join(memoryDir, "events.ndjson");
const indexPath = path.join(memoryDir, "index.json");
const rulesPath = path.join(memoryDir, "rules.md");
const autoRulesPath = path.join(memoryDir, "auto_rules.md");

const AUTO_START = "<!-- AUTO_PROMOTED_RULES_START -->";
const AUTO_END = "<!-- AUTO_PROMOTED_RULES_END -->";

function defaultRules() {
  return `# Memory Rules

## User Preferences
- Use repo-local agent files under \`.agents/\`.

## Operating Rules
- Read \`.agents/napkin.md\` and this file before substantial work.
- Inject at most 5 ranked memories into context.
- Log self mistakes and user corrections as events.
`;
}

function defaultAutoRules() {
  return `# Auto Promoted Memory Rules

This file is generated by \`bash .agents/hooks/codex-autopilot.sh checkpoint\`.
Do not edit it manually.

## Promoted Rules
_No auto-promoted rules yet._
`;
}

function defaultIndex() {
  return {
    version: 1,
    updatedAt: new Date().toISOString(),
    totals: { events: 0 },
    bySource: {},
    byTrigger: {},
    byTag: {},
    topMistakes: [],
    recentEventIds: [],
  };
}

function ensureLayout() {
  fs.mkdirSync(memoryDir, { recursive: true });

  if (!fs.existsSync(eventsPath)) {
    fs.writeFileSync(eventsPath, "", "utf8");
  }

  if (!fs.existsSync(indexPath)) {
    fs.writeFileSync(
      indexPath,
      `${JSON.stringify(defaultIndex(), null, 2)}\n`,
      "utf8",
    );
  }

  if (!fs.existsSync(rulesPath)) {
    fs.writeFileSync(rulesPath, defaultRules(), "utf8");
  }
}

function parseArgs(argv) {
  const args = { _: [] };

  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];

    if (token.startsWith("--")) {
      const key = token.slice(2);
      const next = argv[i + 1];

      if (next && !next.startsWith("--")) {
        args[key] = next;
        i += 1;
      } else {
        args[key] = true;
      }
    } else {
      args._.push(token);
    }
  }

  return args;
}

function tokenize(value) {
  return [
    ...new Set(
      String(value || "")
        .toLowerCase()
        .split(/[^a-z0-9@/_-]+/)
        .map((part) => part.trim())
        .filter((part) => part.length >= 3),
    ),
  ];
}

function normalize(value) {
  return String(value || "")
    .toLowerCase()
    .replace(/\s+/g, " ")
    .trim();
}

function escapeCell(value) {
  return String(value || "")
    .replace(/\|/g, "\\|")
    .replace(/\n/g, " ")
    .trim();
}

function parseNumber(value, fallback) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function readEvents() {
  if (!fs.existsSync(eventsPath)) {
    return [];
  }

  const raw = fs.readFileSync(eventsPath, "utf8").trim();
  if (!raw) {
    return [];
  }

  const events = [];
  const lines = raw.split("\n");

  for (const line of lines) {
    if (!line.trim()) {
      continue;
    }

    try {
      const parsed = JSON.parse(line);
      events.push(parsed);
    } catch {
      // Skip malformed lines to preserve append-only behavior.
    }
  }

  return events;
}

function readRuleBullets() {
  return [
    ...readRuleBulletsFromFile(rulesPath, { skipLegacyAutoSection: true }),
    ...readRuleBulletsFromFile(autoRulesPath),
  ];
}

function readRuleBulletsFromFile(
  filePath,
  { skipLegacyAutoSection = false } = {},
) {
  if (!fs.existsSync(filePath)) {
    return [];
  }

  const lines = fs.readFileSync(filePath, "utf8").split("\n");
  let section = "rules";
  const notes = [];
  let insideLegacyAutoSection = false;

  for (const line of lines) {
    if (skipLegacyAutoSection && line.includes(AUTO_START)) {
      insideLegacyAutoSection = true;
      continue;
    }

    if (skipLegacyAutoSection && line.includes(AUTO_END)) {
      insideLegacyAutoSection = false;
      continue;
    }

    if (insideLegacyAutoSection) {
      continue;
    }

    const heading = line.match(/^##\s+(.+)$/);
    if (heading) {
      section = heading[1].trim();
      continue;
    }

    const bullet = line.match(/^-\s+(.+)$/);
    if (bullet) {
      notes.push({
        type: "rule",
        id: `rule:${section}:${bullet[1]}`,
        section,
        text: bullet[1].trim(),
      });
    }
  }

  return notes;
}

function writeIndex(index) {
  fs.writeFileSync(indexPath, `${JSON.stringify(index, null, 2)}\n`, "utf8");
}

function readIndex() {
  if (!fs.existsSync(indexPath)) {
    return null;
  }

  try {
    return JSON.parse(fs.readFileSync(indexPath, "utf8"));
  } catch {
    return null;
  }
}

function comparableIndexShape(value) {
  return {
    version: value?.version ?? 1,
    totals: value?.totals ?? { events: 0 },
    bySource: value?.bySource ?? {},
    byTrigger: value?.byTrigger ?? {},
    byTag: value?.byTag ?? {},
    topMistakes: value?.topMistakes ?? [],
    recentEventIds: value?.recentEventIds ?? [],
  };
}

function rebuildIndex({ silent = false } = {}) {
  ensureLayout();
  const events = readEvents();

  const bySource = {};
  const byTrigger = {};
  const byTag = {};
  const mistakeCounts = {};

  for (const event of events) {
    const source = event.source || "unknown";
    const trigger = event.trigger || "unknown";

    bySource[source] = (bySource[source] || 0) + 1;
    byTrigger[trigger] = (byTrigger[trigger] || 0) + 1;

    for (const tag of event.tags || []) {
      byTag[tag] = (byTag[tag] || 0) + 1;
    }

    const mistakeKey = normalize(event.mistake);
    if (mistakeKey) {
      mistakeCounts[mistakeKey] = (mistakeCounts[mistakeKey] || 0) + 1;
    }
  }

  const topMistakes = Object.entries(mistakeCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 20)
    .map(([mistake, count]) => ({ mistake, count }));

  const nextComparable = {
    version: 1,
    totals: { events: events.length },
    bySource,
    byTrigger,
    byTag,
    topMistakes,
    recentEventIds: events
      .slice(-20)
      .reverse()
      .map((event) => event.id),
  };

  const existing = readIndex();
  const existingComparable = comparableIndexShape(existing);
  const changed =
    JSON.stringify(existingComparable) !== JSON.stringify(nextComparable);

  let index;

  if (changed) {
    index = {
      ...nextComparable,
      updatedAt: new Date().toISOString(),
    };
    writeIndex(index);
  } else {
    index = {
      ...nextComparable,
      updatedAt: existing?.updatedAt || new Date().toISOString(),
    };
  }

  if (!silent) {
    console.log(JSON.stringify(index, null, 2));
  }
}

function commandAdd(args) {
  ensureLayout();

  const source = String(args.source || "").trim();
  const trigger = String(args.trigger || "").trim();
  const mistake = String(args.mistake || "").trim();
  const correction = String(args.correction || "").trim();
  const allowedSources = new Set(["self", "user", "system", "tool"]);

  if (!source || !trigger || !mistake || !correction) {
    throw new Error(
      "Missing required fields. Use --source --trigger --mistake --correction.",
    );
  }

  if (!allowedSources.has(source)) {
    throw new Error("Invalid --source. Use one of: self, user, system, tool.");
  }

  const confidence = clamp(parseNumber(args.confidence, 0.8), 0, 1);
  const severity = clamp(Math.round(parseNumber(args.severity, 1)), 0, 3);
  const tags = [
    ...new Set(
      String(args.tags || "")
        .split(",")
        .map((tag) => normalize(tag))
        .filter(Boolean),
    ),
  ];

  const timestamp = new Date().toISOString();
  const event = {
    id: `${timestamp.replace(/\D/g, "").slice(0, 14)}-${crypto.randomUUID().slice(0, 8)}`,
    timestamp,
    date: timestamp.slice(0, 10),
    source,
    trigger,
    mistake,
    correction,
    tags,
    confidence,
    severity,
  };

  fs.appendFileSync(eventsPath, `${JSON.stringify(event)}\n`, "utf8");
  rebuildIndex({ silent: true });

  console.log(JSON.stringify({ status: "ok", event }, null, 2));
}

function scoreEvent(event, queryTokens, freqByKey, nowMs) {
  const trigger = normalize(event.trigger);
  const mistake = normalize(event.mistake);
  const correction = normalize(event.correction);
  const tags = (event.tags || []).map((tag) => normalize(tag));
  const blob = `${trigger} ${mistake} ${correction} ${tags.join(" ")}`;

  let score = queryTokens.length ? 0 : 1;

  for (const token of queryTokens) {
    if (trigger.includes(token)) {
      score += 4;
    }

    if (tags.includes(token)) {
      score += 3;
    }

    if (mistake.includes(token)) {
      score += 2;
    }

    if (correction.includes(token)) {
      score += 2;
    }

    if (blob.includes(token)) {
      score += 1;
    }
  }

  const ageDays = Math.max(
    0,
    (nowMs - Date.parse(event.timestamp || nowMs)) / 86400000,
  );
  const recencyScore = Math.max(0, 30 - ageDays) / 30;

  score += recencyScore * 2;
  score += clamp(parseNumber(event.confidence, 0.5), 0, 1) * 1.5;
  score += clamp(parseNumber(event.severity, 1), 0, 3) * 1.2;

  const freqKey = `${trigger}|${mistake}|${correction}`;
  const freq = freqByKey[freqKey] || 1;
  score += Math.min(2, (freq - 1) * 0.5);

  return score;
}

function scoreRule(rule, queryTokens) {
  const text = normalize(rule.text);

  let score = queryTokens.length ? 0 : 1;

  for (const token of queryTokens) {
    if (text.includes(token)) {
      score += 2;
    }
  }

  if (rule.section.toLowerCase().includes("user preferences")) {
    score += 1.5;
  }

  if (rule.section.toLowerCase().includes("operating")) {
    score += 1;
  }

  return score;
}

function commandRank(args) {
  ensureLayout();

  const query = String(args.query || "").trim();
  const limit = Math.max(1, Math.round(parseNumber(args.limit, 5)));
  const format = String(args.format || "json").toLowerCase();

  const queryTokens = tokenize(query);
  const events = readEvents();
  const rules = readRuleBullets();
  const nowMs = Date.now();

  const freqByKey = {};
  for (const event of events) {
    const key = `${normalize(event.trigger)}|${normalize(event.mistake)}|${normalize(event.correction)}`;
    freqByKey[key] = (freqByKey[key] || 0) + 1;
  }

  const rankedEvents = events.map((event) => {
    const score = scoreEvent(event, queryTokens, freqByKey, nowMs);
    return {
      type: "event",
      id: event.id,
      score,
      timestamp: event.timestamp,
      source: event.source,
      trigger: event.trigger,
      mistake: event.mistake,
      correction: event.correction,
      tags: event.tags || [],
    };
  });

  const rankedRules = rules.map((rule) => ({
    type: "rule",
    id: rule.id,
    score: scoreRule(rule, queryTokens),
    section: rule.section,
    text: rule.text,
  }));

  const items = [...rankedEvents, ...rankedRules]
    .sort((a, b) => {
      if (b.score !== a.score) {
        return b.score - a.score;
      }

      const aTime = Date.parse(a.timestamp || 0);
      const bTime = Date.parse(b.timestamp || 0);
      return bTime - aTime;
    })
    .slice(0, limit);

  if (format === "markdown") {
    if (!items.length) {
      console.log("- No memories found.");
      return;
    }

    for (const item of items) {
      if (item.type === "event") {
        console.log(`- [event] (${item.source}) trigger: ${item.trigger}`);
        console.log(`  mistake: ${item.mistake}`);
        console.log(`  correction: ${item.correction}`);
      } else {
        console.log(`- [rule] ${item.section}: ${item.text}`);
      }
    }

    return;
  }

  console.log(
    JSON.stringify(
      {
        query,
        queryTokens,
        count: items.length,
        items,
      },
      null,
      2,
    ),
  );
}

function commandPromote(args) {
  ensureLayout();

  const threshold = Math.max(2, Math.round(parseNumber(args.threshold, 2)));
  const events = readEvents();

  const groups = new Map();

  for (const event of events) {
    const trigger = normalize(event.trigger);
    const mistake = normalize(event.mistake);
    const correction = normalize(event.correction);

    if (!trigger || !mistake || !correction) {
      continue;
    }

    const key = `${trigger}|${mistake}|${correction}`;

    if (!groups.has(key)) {
      groups.set(key, {
        trigger: event.trigger,
        mistake: event.mistake,
        correction: event.correction,
        count: 0,
        firstSeen: event.date || (event.timestamp || "").slice(0, 10),
        lastSeen: event.date || (event.timestamp || "").slice(0, 10),
        tags: new Set(),
      });
    }

    const group = groups.get(key);
    group.count += 1;
    const eventDate = event.date || (event.timestamp || "").slice(0, 10);

    if (eventDate && eventDate < group.firstSeen) {
      group.firstSeen = eventDate;
    }

    if (eventDate && eventDate > group.lastSeen) {
      group.lastSeen = eventDate;
    }

    for (const tag of event.tags || []) {
      group.tags.add(tag);
    }
  }

  const promotions = [...groups.values()]
    .filter((group) => group.count >= threshold)
    .sort((a, b) => b.count - a.count);

  const rows = promotions.map((promotion) => {
    const tags = [...promotion.tags].join(", ") || "none";
    const rule = `When ${promotion.trigger}, avoid ${promotion.mistake}; instead ${promotion.correction}.`;
    return `- count=${promotion.count}; first=${escapeCell(promotion.firstSeen)}; last=${escapeCell(promotion.lastSeen)}; trigger="${escapeCell(promotion.trigger)}"; rule="${escapeCell(rule)}"; tags="${escapeCell(tags)}"`;
  });

  const promotedText = rows.length ? rows.join("\n") : "- (none yet)";
  const autoRules = rows.length
    ? [
        "# Auto Promoted Memory Rules",
        "",
        "This file is generated by `bash .agents/hooks/codex-autopilot.sh checkpoint`.",
        "Do not edit it manually.",
        "",
        "## Promoted Rules",
        promotedText,
        "",
      ].join("\n")
    : defaultAutoRules();

  fs.writeFileSync(autoRulesPath, autoRules, "utf8");
  rebuildIndex({ silent: true });

  console.log(
    JSON.stringify(
      {
        status: "ok",
        threshold,
        promotedCount: promotions.length,
      },
      null,
      2,
    ),
  );
}

function printHelp() {
  console.log(`memory_cli.mjs

Commands:
  add --source <self|user|system|tool> --trigger <text> --mistake <text> --correction <text> [--tags a,b] [--confidence 0..1] [--severity 0..3]
  rank [--query <text>] [--limit <n>] [--format json|markdown]
  rebuild-index
  promote [--threshold <n>]
`);
}

function main() {
  ensureLayout();

  const command = process.argv[2];
  const args = parseArgs(process.argv.slice(3));

  if (
    !command ||
    command === "help" ||
    command === "--help" ||
    command === "-h"
  ) {
    printHelp();
    return;
  }

  if (command === "add") {
    commandAdd(args);
    return;
  }

  if (command === "rank") {
    commandRank(args);
    return;
  }

  if (command === "rebuild-index") {
    rebuildIndex();
    return;
  }

  if (command === "promote") {
    commandPromote(args);
    return;
  }

  throw new Error(`Unknown command: ${command}`);
}

try {
  main();
} catch (error) {
  console.error(String(error.message || error));
  process.exit(1);
}
