export type TokenSource = {
  color: {
    dark: {
      bg: string;
      surface1: string;
      surface2: string;
      surface3: string;
      borderSubtle: string;
      borderStrong: string;
      text: string;
      textMuted: string;
      textFaint: string;
      accent: string;
      accentSoft: string;
      positive: string;
      negative: string;
      warning: string;
      info: string;
    };
    light: {
      bg: string;
      surface1: string;
      surface2: string;
      surface3: string;
      borderSubtle: string;
      borderStrong: string;
      text: string;
      textMuted: string;
      textFaint: string;
      accent: string;
      accentSoft: string;
      positive: string;
      negative: string;
      warning: string;
      info: string;
    };
    bg: string;
    surface1: string;
    surface2: string;
    surface3: string;
    borderSubtle: string;
    borderStrong: string;
    text: string;
    textMuted: string;
    textFaint: string;
    accent: string;
    accentSoft: string;
    positive: string;
    negative: string;
    warning: string;
    info: string;
    brand500: string;
    brand700: string;
    gold500: string;
    surfaceLight: string;
    surfaceDark: string;
    surfaceMutedLight: string;
    surfaceMutedDark: string;
    textLight: string;
    textLightMuted: string;
    textDark: string;
    textDarkMuted: string;
    success500: string;
    error500: string;
    warning500: string;
    info500: string;
    border: string;
  };
  type: {
    h1: { size: number; weight: string; lh: number };
    h2: { size: number; weight: string; lh: number };
    numXXL: { size: number; weight: string; lh: number; tabular: boolean };
    numXL: { size: number; weight: string; lh: number; tabular: boolean };
    num: { size: number; weight: string; lh: number; tabular: boolean };
    body: { size: number; weight: string; lh: number };
    meta: { size: number; weight: string; lh: number };
    labelCaps: { size: number; weight: string; lh: number };
  };
  space: {
    xs: number;
    sm: number;
    md: number;
    lg: number;
    xl: number;
    xxl: number;
  };
  radius: { xs: number; sm: number; md: number; lg: number; xl: number };
  hit: { min: number };
  shadow: { card: string };
};

export const tokenSource: TokenSource;
